services:
  - type: web
    name: doosool-birthday
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
